### PR TITLE
feat: support powershell

### PR DESCRIPTION
**Pull request by artiga033**
#14

### CODE REVIEW

**Comment by artiga033** [comment]
Needs further work, The command_not_found does not work yet. 

The patch https://github.com/iffse/pay-respects/pull/12/commits/ed2a2040b4d19f94276123170ec0e43503faef34#diff-5bf5ae12e63725209487d4de26d9a2bd9696e7beffb5cf984898c8d864d3721aL1-R89 breaks how it works in a pure Windows environment. 

I think we need a way to distinguish msys/cygwin from pure Windows, as the old behavior works fine when on pure Windows.
@mokurin000 I wonder if you are willing to change the way of detecting msys2 environment instead of directly detecting Windows OS?

**Comment by mokurin000** [comment]
> Needs further work, The command_not_found does not work yet.
> 
> The patch [ed2a204#diff-5bf5ae12e63725209487d4de26d9a2bd9696e7beffb5cf984898c8d864d3721aL1-R89](https://github.com/iffse/pay-respects/commit/ed2a2040b4d19f94276123170ec0e43503faef34#diff-5bf5ae12e63725209487d4de26d9a2bd9696e7beffb5cf984898c8d864d3721aL1-R89) breaks how it works in a pure Windows environment.
> MSYS2_PATH
> I think we need a way to distinguish msys/cygwin from pure Windows, as the old behavior works fine when on pure Windows. @mokurin000 I wonder if you are willing to change the way of detecting msys2 environment instead of directly detecting Windows OS?

You can check `MSYS2_PATH`, maybe
I've checked official site of msys2, they said nothing about possible environment variables to detect a msys2 environment

**Comment by artiga033** [comment]
> update: you can implement a `get_path_list` function, e.g. For native windows paths, PR should use `;` to split them update 2: `MSYSTEM` is also defined in Git Bash MIngW64 environment. They also provide `cygpath`

thanks,I'll try it later, as long as it dont affect msys2 environment,after all pure windows will never have variables like this

**Comment by mokurin000** [comment]
> > update: you can implement a `get_path_list` function, e.g. For native windows paths, PR should use `;` to split them update 2: `MSYSTEM` is also defined in Git Bash MIngW64 environment. They also provide `cygpath`
> 
> thanks,I'll try it later, as long as it dont affect msys2 environment,after all pure windows will never have variables like this

Yep. Unless someone blow up their environment, which is not the case we should handle
Just check if 'MSYSTEM' exists, no need to validate

**Comment by iffse** [comment]
Tested on `pwsh` for linux, works well. Nice job!

**Comment by iffse** [comment]
Looks like arguments can't be passed to the `CommandNotFoundAction` because of [powershell's limitation](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.commandlookupeventargs?view=powershellsdk-7.4.0)

**Pull request merged**
